spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/laboratory_monitoring_db

server:
  port: 8080

logging:
  level:
    root: INFO
    com.labo.monitoring: DEBUG
    org.springframework.data.mongodb: DEBUG